rails_tutorial: https://www.railstutorial.org/
rails_tutorial_help: https://www.railstutorial.org/help
rails_tutorial_book: https://www.railstutorial.org/book
rails_tutorial_contact: https://www.railstutorial.org/contact
screen_casts_rails_tutorial: http://screencasts.railstutorial.org/
ruby_on_rails: http://rubyonrails.org/
new_rails: https://new.railstutorial.org/
michael_hartl: https://www.michaelhartl.com/
home_pages: home
help_pages: help
contact_pages: contact
about_pages: about
en: en
vi: vi
